# Generated by Django 5.1.4 on 2024-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trafficevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(max_length=255)),
                ('penalty_category', models.CharField(max_length=255)),
                ('borough', models.CharField(max_length=255)),
                ('neighborhood_council', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('penalty_number', models.IntegerField()),
                ('year', models.CharField(max_length=255)),
                ('quarter', models.IntegerField()),
            ],
        ),
    ]
